name: Generate Datas

on:
  schedule:
    - cron: '*/59 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: generate datas
        uses: Platane/snk@master
        with:
          github_user_name: MrMoorhouse
          svg_out_path: dist/github-contribution-grid-snake.svg
